/*
Headgear bundles (YuEmod)
*/
/* Altyn */
["YuEAltyn","YuE_A","F","F_"],
["YuEAltyn","YuE_AB","F","F_"],
["YuEAltyness_db","YuE_AB","VD","VD_"],
["YuEAltyness_tb","YuE_AB","VU","VU_"],
["YuEAltyness_d","YuE_A","VD","VD_"],
["YuEAltyness_t","YuE_A","VU","VU_"],
/*AltynOld*/
["YuEAltyn_old","YuE_AO","F","F_"],
["YuEAltyn_old","YuE_AOB","F","F_"],
["YuEAltyness_db_old","YuE_AOB","VD","VD_"],
["YuEAltyness_tb_old","YuE_AOB","VU","VU_"],
["YuEAltyness_d_old","YuE_AO","VD","VD_"],
["YuEAltyness_t_old","YuE_AO","VU","VU_"],
/*AltynZbrlOld*/
["YuEAltynZbrl_d_old","YuE_AZbrO","VD","VD_"],
["YuEAltynZbrl_t_old","YuE_AZbrO","VU","VU_"],
/*AltynZbrl*/
["YuEAltynZbrl_d","YuE_AZbr","VD","VD_"],
["YuEAltynZbrl_t","YuE_AZbr","VU","VU_"],
/* BandanaA */
["YuEBandana_A","YuE_BaA","F","F_"],
["YuEBandana_A_GBSHP2","YuE_BaA","HF","HF_"],
["YuEBandanaEss_A","YuE_BaA","HF","HF_"],
/*BandanaB */
["YuEBandana_B","YuE_BaBA","F","F_"],
["YuEBandana_B_GBSHP2","YuE_BaBA","HF","HF_"],
["YuEBandanaEss_B","YuE_BaBA","HF","HF_"],
/* BandanaBS */
["YuEBandana_BS","YuE_BaBSA","F","F_"],
["YuEBandana_BS_GBSHP2","YuE_BaBSA","HF","HF_"],
["YuEBandanaEss_Bb","YuE_BaBSA","HF","HF_"],
/* BandanaBl */
["YuEBandana_BL","YuE_BaBLA","F","F_"],
["YuEBandana_BL_GBSHP2","YuE_BaBLA","HF","HF_"],
/* BandanaD */
["YuEBandana_D","YuE_BaDA","F","F_"],
["YuEBandana_D_GBSHP2","YuE_BaDA","HF","HF_"],
/* BandanaEMP */
["YuEBandana_E","YuE_BaEA","F","F_"],
["YuEBandana_E_GBSHP2","YuE_BaEA","HF","HF_"],
["YuEBandanaEss_Emp","YuE_BaEA","HF","HF_"],
/*BandanaFlora*/
["YuEBandana_Fl","YuE_BaFLA","F","F_"],
["YuEBandana_Fl_GBSHP2","YuE_BaFLA","HF","HF_"],
["YuEBandanaEss_Fl","YuE_BaFLA","HF","HF_"],
/*BandanaFrog*/
["YuEBandana_Fr","YuE_BaFrA","F","F_"],
["YuEBandana_Fr_GBSHP2","YuE_BaFrA","HF","HF_"],
["YuEBandanaEss_Fr","YuE_BaFrA","HF","HF_"],
/*BandanaG*/
["YuEBandana_G","YuE_BaGA","F","F_"],
["YuEBandana_G_GBSHP2","YuE_BaGA","HF","HF_"],
["YuEBandanaEss_G","YuE_BaGA","HF","HF_"],
/*BandanaO*/
["YuEBandana_O","YuE_BaOA","F","F_"],
["YuEBandana_O_GBSHP2","YuE_BaOA","HF","HF_"],
["YuEBandanaEss_O","YuE_BaOA","HF","HF_"],
/*BandanaS*/
["YuEBandana_S","YuE_BaSA","F","F_"],
["YuEBandana_S_GBSHP2","YuE_BaSA","HF","HF_"],
["YuEBandanaEss_S","YuE_BaSA","HF","HF_"],
/*GBSHP2*/
["YuEGBSHP2b","YuE_GBSH","F","F_"],
["YuEBandanaEss_S","YuE_BaSA","HF","HF_"],
["YuEBandanaEss_O","YuE_BaOA","HF","HF_"],
["YuEBandanaEss_G","YuE_BaGA","HF","HF_"],
["YuEBandanaEss_Fl","YuE_BaFlA","HF","HF_"],
["YuEBandanaEss_Fr","YuE_BaFeA","HF","HF_"],
["YuEBandanaEss_Emp","YuE_BaEA","HF","HF_"],
["YuEBandanaEss_Bb","YuE_BabbA","HF","HF_"],
["YuEBandanaEss_B","YuE_BaBA","HF","HF_"],
["YuEBandanaEss_A","YuE_BaA","HF","HF_"],
/*K6*/
["YuEK6_3","YuE_K6-3G","F","F_"],
["YuEK6_3_Ess_d","YuE_K6-3G","VD","VD_"],
["YuEK6_3_Ess_t","YuE_K6-3G","VU","VU_"], /* Зелёная */ 
["YuEK6_3B","YuE_K6-3B","F","F_"],
["YuEK6_3B_Ess_d","YuE_K6-3B","VD","VD_"],
["YuEK6_3B_Ess_t","YuE_K6-3B","VU","VU_"], /* Чёрная */ 
["YuEK6_3_EssB_d","YuE_K6-3GB","VD","VD_"],
["YuEK6_3_EssB_t","YuE_K6-3GB","VU","VU_"], /* Зелёная */ 
["YuEK6_3B_EssB_d","YuE_K6-3BB","VD","VD_"],
["YuEK6_3B_EssB_t","YuE_K6-3BB","VU","VU_"], /* Чёрная */
/*K6Zbr*/
["YuEK6_3BZbrl_t","YuE_K6-3ZbrB","VU","VU_"],
["YuEK6_3BZbrl_d","YuE_K6-3ZbrB","VD","VD_"],
["YuEK6_3Zbrl_t","YuE_K6-3Zbr","VU","VU_"],
["YuEK6_3Zbrl_d","YuE_K6-3Zbr","VD","VD_"],
/*Maska*/
["YuEMaska1","YuE_M","F","F_"],
["YuEMaska1EssD","YuE_M","VD","VD_"],
["YuEMaska1EssT","YuE_M","VU","VU_"],
["YuEMaska1EssBD","YuE_MB","VD","VD_"],
["YuEMaska1EssBT","YuE_MB","VU","VU_"],
["YuEMaska1zbrD","YuE_ZbrM","VD","VD_"],
["YuEMaska1zbrT","YuE_ZbrM","VU","VU_"],
/*Panama1*/
["YuEPanama1a","YuE_Pa1","F","F_"],
["YuEPanama1a_GBSHP2","YuE_Pa1","HF","HF_"],

["YuEPanama1b","YuE_Pa2","F","F_"],
["YuEPanama1b_GBSHP2","YuE_Pa2","HF","HF_"],

["YuEPanama1b2","YuE_Pa3","F","F_"],
["YuEPanama1b_GBSHP22","YuE_Pa3","HF","HF_"],

["YuEPanama1e","YuE_Pa4","F","F_"],
["YuEPanama1e_GBSHP2","YuE_Pa4","HF","HF_"],

["YuEPanama1fl","YuE_Pa5","F","F_"],
["YuEPanama1fl_GBSHP2","YuE_Pa5","HF","HF_"],

["YuEPanama1fr","YuE_Pa6","F","F_"],
["YuEPanama1fr_GBSHP2","YuE_Pa6","HF","HF_"],

["YuEPanama1g","YuE_Pa7","F","F_"],
["YuEPanama1g_GBSHP2","YuE_Pa7","HF","HF_"],

["YuEPanama1o","YuE_Pa8","F","F_"],
["YuEPanama1o_GBSHP2","YuE_Pa8","HF","HF_"],

["YuEPanama1s","YuE_Pa9","F","F_"],
["YuEPanama1s_GBSHP2","YuE_Pa9","HF","HF_"],
/*Panama1b*/
["YuEPanama1ba","YuE_Pa11","F","F_"],
["YuEPanama1ba_GBSHP2","YuE_Pa11","HF","HF_"],

["YuEPanama1bb","YuE_Pa12","F","F_"],
["YuEPanama1bb_GBSHP2","YuE_Pa12","HF","HF_"],

["YuEPanama1bb2","YuE_Pa13","F","F_"],
["YuEPanama1bb2_GBSHP2","YuE_Pa13","HF","HF_"],

["YuEPanama1be","YuE_Pa14","F","F_"],
["YuEPanama1be_GBSHP2","YuE_Pa14","HF","HF_"],

["YuEPanama1bfl","YuE_Pa15","F","F_"],
["YuEPanama1bfl_GBSHP2","YuE_Pa15","HF","HF_"],

["YuEPanama1bfr","YuE_Pa16","F","F_"],
["YuEPanama1bfr_GBSHP2","YuE_Pa16","HF","HF_"],

["YuEPanama1bg","YuE_Pa17","F","F_"],
["YuEPanama1bg_GBSHP2","YuE_Pa17","HF","HF_"],

["YuEPanama1bo","YuE_Pa18","F","F_"],
["YuEPanama1bo_GBSHP2","YuE_Pa18","HF","HF_"],

["YuEPanama1bs","YuE_Pa19","F","F_"],
["YuEPanama1bs_GBSHP2","YuE_Pa19","HF","HF_"],
/*Panama2*/
["YuEPanama2a","YuE_Pa31","F","F_"],
["YuEPanama2a_GBSHP2","YuE_Pa31","HF","HF_"],

["YuEPanama2b","YuE_Pa32","F","F_"],
["YuEPanama2b_GBSHP2","YuE_Pa32","HF","HF_"],

["YuEPanama2b2","YuE_Pa33","F","F_"],
["YuEPanama2b2_GBSHP2","YuE_Pa33","HF","HF_"],

["YuEPanama2e","YuE_Pa34","F","F_"],
["YuEPanama2e_GBSHP2","YuE_Pa34","HF","HF_"],

["YuEPanama2fl","YuE_Pa35","F","F_"],
["YuEPanama2fl_GBSHP2","YuE_Pa35","HF","HF_"],

["YuEPanama2fr","YuE_Pa36","F","F_"],
["YuEPanama2fr_GBSHP2","YuE_Pa36","HF","HF_"],

["YuEPanama2g","YuE_Pa37","F","F_"],
["YuEPanama2g_GBSHP2","YuE_Pa37","HF","HF_"],

["YuEPanama2o","YuE_Pa38","F","F_"],
["YuEPanama2o_GBSHP2","YuE_Pa38","HF","HF_"],

["YuEPanama2s","YuE_Pa39","F","F_"],
["YuEPanama2s_GBSHP2","YuE_Pa39","HF","HF_"],
/*Panama2b*/
["YuEPanama2ba","YuE_Pa21","F","F_"],
["YuEPanama2ba_GBSHP2","YuE_Pa21","HF","HF_"],

["YuEPanama2bb","YuE_Pa22","F","F_"],
["YuEPanama2bb_GBSHP2","YuE_Pa22","HF","HF_"],

["YuEPanama2bb2","YuE_Pa23","F","F_"],
["YuEPanama2bb2_GBSHP2","YuE_Pa23","HF","HF_"],

["YuEPanama2be","YuE_Pa24","F","F_"],
["YuEPanama2be_GBSHP2","YuE_Pa24","HF","HF_"],

["YuEPanama2bfl","YuE_Pa25","F","F_"],
["YuEPanama2bfl_GBSHP2","YuE_Pa25","HF","HF_"],

["YuEPanama2bfr","YuE_Pa26","F","F_"],
["YuEPanama2bfr_GBSHP2","YuE_Pa26","HF","HF_"],

["YuEPanama2bg","YuE_Pa27","F","F_"],
["YuEPanama2bg_GBSHP2","YuE_Pa27","HF","HF_"],

["YuEPanama2bo","YuE_Pa28","F","F_"],
["YuEPanama2bo_GBSHP2","YuE_Pa28","HF","HF_"],

["YuEPanama2bs","YuE_Pa29","F","F_"],
["YuEPanama2bs_GBSHP2","YuE_Pa29","HF","HF_"],
/*RisB*/
["YuERisB","YuE_RisB","F","F_"],
["YuERisB_Ess_d","YuE_RisB","VD","VD_"],
["YuERisB_Ess_t","YuE_RisB","VU","VU_"],
["YuERisB_EssB_d","YuE_RisBB","VD","VD_"],
["YuERisB_EssB_t","YuE_RisBB","VU","VU_"],
["YuERisBZbrl_d","YuE_RisZbrB","VD","VD_"],
["YuERisBZbrl_t","YuE_RisZbrB","VU","VU_"],
/*RisG*/
["YuERis","YuE_Risg","F","F_"],
["YuERis_Ess_d","YuE_Risg","VD","VD_"],
["YuERis_Ess_t","YuE_Risg","VU","VU_"],
["YuERis_EssB_d","YuE_RisBg","VD","VD_"],
["YuERis_EssB_t","YuE_RisBg","VU","VU_"],
["YuERisZbrl_d","YuE_RisZbrg","VD","VD_"],
["YuERisZbrl_t","YuE_RisZbrg","VU","VU_"],
/*ZH1*/
["YuEZH1EssD","YuE_ZH3Zbr","VD","VD_"],
["YuEZH1EssT","YuE_ZH3Zbr","VD","VD_"],
["YuEZH1EssbD","YuE_ZH3Zbrb","VD","VD_"],
["YuEZH1EssbT","YuE_ZH3Zbrb","VD","VD_"],
/*ZH1_m2*/
["YuEZH1_2m","YuE_ZH1_m2","F","F_"],
["YuEZH1_2mEssbd","YuE_ZH1B","VD","VD_"],
["YuEZH1_2mEssbT","YuE_ZH1B","VU","VU_"],
["YuEZH1_2mEssd","YuE_ZH1","VD","VD_"],
["YuEZH1_2mEssT","YuE_ZH1","VU","VU_"],
/*ZH1_m2Zbr*/
["YuEZH1_2m_Zd","YuE_ZHZbr","VD","VD_"],
["YuEZH1_2m_Zt","YuE_ZHZbr","VU","VU_"],
["YuEZH1_2m_zt_Ch_a","YuE_ZHZbrA","VU","VU_"],
["YuEZH1_2m_zd_Ch_a","YuE_ZHZbrA","VD","VD_"],
["YuEZH1_2m_zt_Ch_be","YuE_ZHZbrbe","VU","VU_"],
["YuEZH1_2m_zd_Ch_be","YuE_ZHZbrbe","VD","VD_"],
["YuEZH1_2m_zt_Ch_be2","YuE_ZHZbrbe2","VU","VU_"],
["YuEZH1_2m_zd_Ch_be2","YuE_ZHZbrbe2","VD","VD_"],
["YuEZH1_2m_zt_Ch_b","YuE_ZHZbrb","VU","VU_"],
["YuEZH1_2m_zd_Ch_b","YuE_ZHZbrb","VD","VD_"],
["YuEZH1_2m_zt_Ch_fo","YuE_ZHZbrfo","VU","VU_"],
["YuEZH1_2m_zd_Ch_fo","YuE_ZHZbrfo","VD","VD_"],
["YuEZH1_2m_zt_Ch_iz","YuE_ZHZbriz","VU","VU_"],
["YuEZH1_2m_zd_Ch_iz","YuE_ZHZbriz","VD","VD_"],
["YuEZH1_2m_zt_Ch_o","YuE_ZHZbro","VU","VU_"],
["YuEZH1_2m_zd_Ch_o","YuE_ZHZbro","VD","VD_"],
["YuEZH1_2m_zt_Ch_s","YuE_ZHZbrs","VU","VU_"],
["YuEZH1_2m_zd_Ch_s","YuE_ZHZbrs","VD","VD_"],
["YuEZH1_2m_zt_Ch_frog","YuE_ZHZbrfrog","VU","VU_"],
["YuEZH1_2m_zd_Ch_frog","YuE_ZHZbrfrogo","VD","VD_"],
["YuEZH1_2m_zt_Ch_osen","YuE_ZHZbrosen","VU","VU_"],
["YuEZH1_2m_zd_Ch_osen","YuE_ZHZbrosen","VD","VD_"],
["YuEZH1_2m_zt_Ch_snow","YuE_ZHZbrsn","VU","VU_"],
["YuEZH1_2m_zd_Ch_snow","YuE_ZHZbrsn","VD","VD_"],
["YuEZH1_2m_zt_Ch_Y","YuE_ZHZbrY","VU","VU_"],
["YuEZH1_2m_zd_Ch_Y","YuE_ZHZbrY","VD","VD_"],
/*ZH1_m2Ess*/
["YuEZH1_2mEsst_Ch_a","YuE_ZHEssA","VU","VU_"],
["YuEZH1_2mEssd_Ch_a","YuE_ZHEssA","VD","VD_"],
["YuEZH1_2mEsst_Ch_be","YuE_ZHEssbe","VU","VU_"],
["YuEZH1_2mEssd_Ch_be","YuE_ZHEssbe","VD","VD_"],
["YuEZH1_2mEsst_Ch_be2","YuE_ZHEssbe2","VU","VU_"],
["YuEZH1_2mEssd_Ch_be2","YuE_ZHEssbe2","VD","VD_"],
["YuEZH1_2mEsst_Ch_b","YuE_ZHEssb","VU","VU_"],
["YuEZH1_2mEssd_Ch_b","YuE_ZHEssb","VD","VD_"],
["YuEZH1_2mEsst_Ch_fo","YuE_ZHEssfo","VU","VU_"],
["YuEZH1_2mEssd_Ch_fo","YuE_ZHEssfo","VD","VD_"],
["YuEZH1_2mEsst_Ch_iz","YuE_ZHEssiz","VU","VU_"],
["YuEZH1_2mEssd_Ch_iz","YuE_ZHEssiz","VD","VD_"],
["YuEZH1_2mEsst_Ch_o","YuE_ZHEsso","VU","VU_"],
["YuEZH1_2mEssd_Ch_o","YuE_ZHEsso","VD","VD_"],
["YuEZH1_2mEsst_Ch_s","YuE_ZHEsss","VU","VU_"],
["YuEZH1_2mEssd_Ch_s","YuE_ZHEsss","VD","VD_"],
["YuEZH1_2mEsst_Ch_frog","YuE_ZHEssfrog","VU","VU_"],
["YuEZH1_2mEssd_Ch_frog","YuE_ZHEssfrogo","VD","VD_"],
["YuEZH1_2mEsst_Ch_osen","YuE_ZHEsssen","VU","VU_"],
["YuEZH1_2mEssd_Ch_osen","YuE_ZHEssosen","VD","VD_"],
["YuEZH1_2mEsst_Ch_snow","YuE_ZHEsssn","VU","VU_"],
["YuEZH1_2mEssd_Ch_snow","YuE_ZHEsssn","VD","VD_"],
["YuEZH1_2mEsst_Ch_Y","YuE_ZHEssY","VU","VU_"],
["YuEZH1_2mEssd_Ch_Y","YuE_ZHEssY","VD","VD_"],
/*ZH1_m2EssB*/
["YuEZH1_2mEssbt_Ch_a","YuE_ZHEssbA","VU","VU_"],
["YuEZH1_2mEssbd_Ch_a","YuE_ZHEssbA","VD","VD_"],
["YuEZH1_2mEssbt_Ch_be","YuE_ZHEssbbe","VU","VU_"],
["YuEZH1_2mEssbd_Ch_be","YuE_ZHEssbbe","VD","VD_"],
["YuEZH1_2mEssbt_Ch_be2","YuE_ZHEssbbe2","VU","VU_"],
["YuEZH1_2mEssbd_Ch_be2","YuE_ZHEssbbe2","VD","VD_"],
["YuEZH1_2mEssbt_Ch_b","YuE_ZHEssbb","VU","VU_"],
["YuEZH1_2mEssbd_Ch_b","YuE_ZHEssbb","VD","VD_"],
["YuEZH1_2mEssbt_Ch_fo","YuE_ZHEssbfo","VU","VU_"],
["YuEZH1_2mEssbd_Ch_fo","YuE_ZHEssbfo","VD","VD_"],
["YuEZH1_2mEssbt_Ch_iz","YuE_ZHEssbiz","VU","VU_"],
["YuEZH1_2mEssbd_Ch_iz","YuE_ZHEssbiz","VD","VD_"],
["YuEZH1_2mEssbt_Ch_o","YuE_ZHEssbo","VU","VU_"],
["YuEZH1_2mEssbd_Ch_o","YuE_ZHEssbo","VD","VD_"],
["YuEZH1_2mEssbt_Ch_s","YuE_ZHEssbs","VU","VU_"],
["YuEZH1_2mEssbd_Ch_s","YuE_ZHEssbs","VD","VD_"],
["YuEZH1_2mEssbt_Ch_frog","YuE_ZHEssbfrog","VU","VU_"],
["YuEZH1_2mEssbd_Ch_frog","YuE_ZHEssbfrogo","VD","VD_"],
["YuEZH1_2mEssbt_Ch_osen","YuE_ZHEssbsen","VU","VU_"],
["YuEZH1_2mEssbd_Ch_osen","YuE_ZHEssbosen","VD","VD_"],
["YuEZH1_2mEssbt_Ch_snow","YuE_ZHEssbsn","VU","VU_"],
["YuEZH1_2mEssbd_Ch_snow","YuE_ZHEssbsn","VD","VD_"],
["YuEZH1_2mEssbt_Ch_Y","YuE_ZHEssbY","VU","VU_"],
["YuEZH1_2mEssbd_Ch_Y","YuE_ZHEssbY","VD","VD_"],
/*ZH1_mr2Zbr*/
["YuEZH1_2mr_Zd","YuE_ZHZbr","VD","VD_"],
["YuEZH1_2mr_Zt","YuE_ZHZbr","VU","VU_"],
["YuEZH1_2mr_zt_Ch_a","YuE_ZHrZbrA","VU","VU_"],
["YuEZH1_2mr_zd_Ch_a","YuE_ZHrZbrA","VD","VD_"],
["YuEZH1_2mr_zt_Ch_be","YuE_ZHrZbrbe","VU","VU_"],
["YuEZH1_2mr_zd_Ch_be","YuE_ZHrZbrbe","VD","VD_"],
["YuEZH1_2mr_zt_Ch_be2","YuE_ZHrZbrbe2","VU","VU_"],
["YuEZH1_2mr_zd_Ch_be2","YuE_ZHrZbrbe2","VD","VD_"],
["YuEZH1_2mr_zt_Ch_b","YuE_ZHrZbrb","VU","VU_"],
["YuEZH1_2mr_zd_Ch_b","YuE_ZHrZbrb","VD","VD_"],
["YuEZH1_2mr_zt_Ch_fo","YuE_ZHrZbrfo","VU","VU_"],
["YuEZH1_2mr_zd_Ch_fo","YuE_ZHrZbrfo","VD","VD_"],
["YuEZH1_2mr_zt_Ch_iz","YuE_ZHrZbriz","VU","VU_"],
["YuEZH1_2mr_zd_Ch_iz","YuE_ZHrZbriz","VD","VD_"],
["YuEZH1_2mr_zt_Ch_o","YuE_ZHrZbro","VU","VU_"],
["YuEZH1_2mr_zd_Ch_o","YuE_ZHrZbro","VD","VD_"],
["YuEZH1_2mr_zt_Ch_s","YuE_ZHrZbrs","VU","VU_"],
["YuEZH1_2mr_zd_Ch_s","YuE_ZHrZbrs","VD","VD_"],
["YuEZH1_2mr_zt_Ch_frog","YuE_ZHrZbrfrog","VU","VU_"],
["YuEZH1_2mr_zd_Ch_frog","YuE_ZHrZbrfrogo","VD","VD_"],
["YuEZH1_2mr_zt_Ch_osen","YuE_ZHrZbrosen","VU","VU_"],
["YuEZH1_2mr_zd_Ch_osen","YuE_ZHrZbrosen","VD","VD_"],
["YuEZH1_2mr_zt_Ch_snow","YuE_ZHrZbrsn","VU","VU_"],
["YuEZH1_2mr_zd_Ch_snow","YuE_ZHrZbrsn","VD","VD_"],
["YuEZH1_2mr_zt_Ch_Y","YuE_ZHrZbrY","VU","VU_"],
["YuEZH1_2mr_zd_Ch_Y","YuE_ZHrZbrY","VD","VD_"],
/*ZH1_m2Ess*/
["YuEZH1_2mrEsst_Ch_a","YuE_ZHrEssA","VU","VU_"],
["YuEZH1_2mrEssd_Ch_a","YuE_ZHrEssA","VD","VD_"],
["YuEZH1_2mrEsst_Ch_be","YuE_ZHrEssbe","VU","VU_"],
["YuEZH1_2mrEssd_Ch_be","YuE_ZHrEssbe","VD","VD_"],
["YuEZH1_2mrEsst_Ch_be2","YuE_ZHrEssbe2","VU","VU_"],
["YuEZH1_2mrEssd_Ch_be2","YuE_ZHrEssbe2","VD","VD_"],
["YuEZH1_2mrEsst_Ch_b","YuE_ZHrEssb","VU","VU_"],
["YuEZH1_2mrEssd_Ch_b","YuE_ZHrEssb","VD","VD_"],
["YuEZH1_2mrEsst_Ch_fo","YuE_ZHrEssfo","VU","VU_"],
["YuEZH1_2mrEssd_Ch_fo","YuE_ZHrEssfo","VD","VD_"],
["YuEZH1_2mrEsst_Ch_iz","YuE_ZHrEssiz","VU","VU_"],
["YuEZH1_2mrEssd_Ch_iz","YuE_ZHrEssiz","VD","VD_"],
["YuEZH1_2mrEsst_Ch_o","YuE_ZHrEsso","VU","VU_"],
["YuEZH1_2mrEssd_Ch_o","YuE_ZHrEsso","VD","VD_"],
["YuEZH1_2mrEsst_Ch_s","YuE_ZHrEsss","VU","VU_"],
["YuEZH1_2mrEssd_Ch_s","YuE_ZHrEsss","VD","VD_"],
["YuEZH1_2mrEsst_Ch_frog","YuE_ZHrEssfrog","VU","VU_"],
["YuEZH1_2mrEssd_Ch_frog","YuE_ZHrEssfrogo","VD","VD_"],
["YuEZH1_2mrEsst_Ch_osen","YuE_ZHrEsssen","VU","VU_"],
["YuEZH1_2mrEssd_Ch_osen","YuE_ZHrEssosen","VD","VD_"],
["YuEZH1_2mrEsst_Ch_snow","YuE_ZHrEsssn","VU","VU_"],
["YuEZH1_2mrEssd_Ch_snow","YuE_ZHrEsssn","VD","VD_"],
["YuEZH1_2mrEsst_Ch_Y","YuE_ZHrEssY","VU","VU_"],
["YuEZH1_2mrEssd_Ch_Y","YuE_ZHrEssY","VD","VD_"],
/*ZH1_mr2EssB*/
["YuEZH1_2mrEssbt_Ch_a","YuE_ZHrEssbA","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_a","YuE_ZHrEssbA","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_be","YuE_ZHrEssbbe","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_be","YuE_ZHrEssbbe","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_be2","YuE_ZHrEssbbe2","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_be2","YuE_ZHrEssbbe2","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_b","YuE_ZHrEssbb","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_b","YuE_ZHrEssbb","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_fo","YuE_ZHrEssbfo","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_fo","YuE_ZHrEssbfo","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_iz","YuE_ZHrEssbiz","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_iz","YuE_ZHrEssbiz","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_o","YuE_ZHrEssbo","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_o","YuE_ZHrEssbo","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_s","YuE_ZHrEssbs","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_s","YuE_ZHrEssbs","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_frog","YuE_ZHrEssbfrog","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_frog","YuE_ZHrEssbfrogo","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_osen","YuE_ZHrEssbsen","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_osen","YuE_ZHrEssbosen","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_snow","YuE_ZHrEssbsn","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_snow","YuE_ZHrEssbsn","VD","VD_"],
["YuEZH1_2mrEssbt_Ch_Y","YuE_ZHrEssbY","VU","VU_"],
["YuEZH1_2mrEssbd_Ch_Y","YuE_ZHrEssbY","VD","VD_"]
