/*
Uniform bundles (YuEmod)
*/

/*
 *	Light 
 */
 
["Peh_Afganka_EAST_Uniform","YuE_Afgan","F","F_"],
["Peh_Afganka_EAST_Uniform2","YuE_Afgan","R","R_"],
["Peh_Afganka_EAST_Uniform3","YuE_AfganO","F","F_"],
["Peh_Afganka_EAST_Uniform4","YuE_AfganO","R","R_"],
["Peh_Afganka_EAST_Uniform5","YuE_Afgan","RJ","RJ_"],
["Peh_Afganka_EAST_Uniform6","YuE_Afgan","RJ","RJ_"],
["Peh_Afganka_EAST_Uniform7","YuE_AfganO","RG","RG_"],
["Peh_Afganka_EAST_Uniform8","YuE_AfganO","RJ","RJ_"],

["Peh_Afganka2_EAST_Uniform","YuE_Afgan2","F","F_"],
["Peh_Afganka2_EAST_Uniform2","YuE_Afgan2","R","R_"],
["Peh_Afganka2_EAST_Uniform3","YuE_Afgan2O","F","F_"],
["Peh_Afganka2_EAST_Uniform4","YuE_Afgan2O","R","R_"],
["Peh_Afganka2_EAST_Uniform5","YuE_Afgan2","RJ","RJ_"],
["Peh_Afganka2_EAST_Uniform6","YuE_Afgan2","RJ","RJ_"],
["Peh_Afganka2_EAST_Uniform7","YuE_Afgan2O","RG","RG_"],
["Peh_Afganka2_EAST_Uniform8","YuE_Afgan2O","RJ","RJ_"],

["Peh_Flora_EAST_Uniform","YuE_Flora1","F","F_"],
["Peh_Flora_EAST_Uniform2","YuE_Flora1","R","R_"],
["Peh_Flora_EAST_Uniform3","YuE_FloraO","F","F_"],
["Peh_Flora_EAST_Uniform4","YuE_FloraO","R","R_"],
["Peh_Flora_EAST_Uniform5","YuE_Flora1","RJ","RJ_"],
["Peh_Flora_EAST_Uniform6","YuE_Flora1","RJ","RJ_"],
["Peh_Flora_EAST_Uniform7","YuE_FloraO","RG","RG_"],
["Peh_Flora_EAST_Uniform8","YuE_FloraO","RJ","RJ_"],

["Peh_FloraButan_EAST_Uniform","YuE_FloraB","F","F_"],
["Peh_FloraButan_EAST_Uniform2","YuE_FloraB","R","R_"],
["Peh_FloraButan_EAST_Uniform3","YuE_FloraBO","F","F_"],
["Peh_FloraButan_EAST_Uniform4","YuE_FloraBO","R","R_"],
["Peh_FloraButan_EAST_Uniform5","YuE_FloraB","RJ","RJ_"],
["Peh_FloraButan_EAST_Uniform6","YuE_FloraB","RJ","RJ_"],
["Peh_FloraButan_EAST_Uniform7","YuE_FloraBO","RG","RG_"],
["Peh_FloraButan_EAST_Uniform8","YuE_FloraBO","RJ","RJ_"],

["Peh_FloraDubok_EAST_Uniform","YuE_FloraD","F","F_"],
["Peh_FloraDubok_EAST_Uniform2","YuE_FloraD","R","R_"],
["Peh_FloraDubok_EAST_Uniform3","YuE_FloraDO","F","F_"],
["Peh_FloraDubok_EAST_Uniform4","YuE_FloraDO","R","R_"],
["Peh_FloraDubok_EAST_Uniform5","YuE_FloraD","RJ","RJ_"],
["Peh_FloraDubok_EAST_Uniform6","YuE_FloraD","RJ","RJ_"],
["Peh_FloraDubok_EAST_Uniform7","YuE_FloraDO","RG","RG_"],
["Peh_FloraDubok_EAST_Uniform8","YuE_FloraDO","RJ","RJ_"],

["Peh_FloraSea_EAST_Uniform","YuE_FloraS","F","F_"],
["Peh_FloraSea_EAST_Uniform2","YuE_FloraS","R","R_"],
["Peh_FloraSea_EAST_Uniform3","YuE_FloraSO","F","F_"],
["Peh_FloraSea_EAST_Uniform4","YuE_FloraSO","R","R_"],
["Peh_FloraSea_EAST_Uniform5","YuE_FloraS","RJ","RJ_"],
["Peh_FloraSea_EAST_Uniform6","YuE_FloraS","RJ","RJ_"],
["Peh_FloraSea_EAST_Uniform7","YuE_FloraSO","RG","RG_"],
["Peh_FloraSea_EAST_Uniform8","YuE_FloraSO","RJ","RJ_"],

["Peh_Floras_EAST_Uniform","YuE_FloraV2","F","F_"],
["Peh_Floras_EAST_Uniform2","YuE_FloraV2","R","R_"],
["Peh_Floras_EAST_Uniform3","YuE_FloraV2O","F","F_"],
["Peh_Floras_EAST_Uniform4","YuE_FloraV2O","R","R_"],
["Peh_Floras_EAST_Uniform5","YuE_FloraV2","RJ","RJ_"],
["Peh_Floras_EAST_Uniform6","YuE_FloraV2","RJ","RJ_"],
["Peh_Floras_EAST_Uniform7","YuE_FloraV2O","RG","RG_"],
["Peh_Floras_EAST_Uniform8","YuE_FloraV2O","RJ","RJ_"],

["Peh_FloraVSR93_EAST_Uniform","YuE_FloraVSR93","F","F_"],
["Peh_FloraVSR93_EAST_Uniform2","YuE_FloraVSR93","R","R_"],
["Peh_FloraVSR93_EAST_Uniform3","YuE_FloraVSR93O","F","F_"],
["Peh_FloraVSR93_EAST_Uniform4","YuE_FloraVSR93O","R","R_"],
["Peh_FloraVSR93_EAST_Uniform5","YuE_FloraVSR93","RJ","RJ_"],
["Peh_FloraVSR93_EAST_Uniform6","YuE_FloraVSR93","RJ","RJ_"],
["Peh_FloraVSR93_EAST_Uniform7","YuE_FloraVSR93O","RG","RG_"],
["Peh_FloraVSR93_EAST_Uniform8","YuE_FloraVSR93O","RJ","RJ_"],

["Peh_FloraVSR93w_EAST_Uniform","YuE_FloraVSR93w","F","F_"],
["Peh_FloraVSR93w_EAST_Uniform2","YuE_FloraVSR93w","R","R_"],
["Peh_FloraVSR93w_EAST_Uniform3","YuE_FloraVSR93wO","F","F_"],
["Peh_FloraVSR93w_EAST_Uniform4","YuE_FloraVSR93wO","R","R_"],
["Peh_FloraVSR93w_EAST_Uniform5","YuE_FloraVSR93w","RJ","RJ_"],
["Peh_FloraVSR93w_EAST_Uniform6","YuE_FloraVSR93w","RJ","RJ_"],
["Peh_FloraVSR93w_EAST_Uniform7","YuE_FloraVSR93wO","RG","RG_"],
["Peh_FloraVSR93w_EAST_Uniform8","YuE_FloraVSR93wO","RJ","RJ_"],
/*
 *	Bushlats 
 */
["Bushlat_VSRAf_EAST_Uniform","YuE_BA","F","F_"],
["Bushlat_VSRNAf_EAST_Uniform","YuE_BnA","F","F_"],
["BushlatVt_VSRAf_EAST_Uniform","YuE_BA","CU","CU_"],
["BushlatVt_VSRNAf_EAST_Uniform","YuE_BnA","CU","CU_"],
["BushlatVtk_VSRAf_EAST_Uniform","YuE_BA","H","H_"],
["BushlatVtk_VSRNAf_EAST_Uniform","YuE_BnA","H","H_"],

["Bushlat_VSRAf2_EAST_Uniform","YuE_BA2","F","F_"],
["Bushlat_VSRNAf2_EAST_Uniform","YuE_BnA2","F","F_"],
["BushlatVt_VSRAf2_EAST_Uniform","YuE_BA2","CU","CU_"],
["BushlatVt_VSRNAf2_EAST_Uniform","YuE_BnA2","CU","CU_"],
["BushlatVtk_VSRAf2_EAST_Uniform","YuE_BA2","H","H_"],
["BushlatVtk_VSRNAf2_EAST_Uniform","YuE_BnA2","H","H_"],

["Bushlat_Flora_EAST_Uniform","YuE_BF","F","F_"],
["BushlatVt_Flora_EAST_Uniform","YuE_BF","CU","CU_"],
["BushlatVtk_Flora_EAST_Uniform","YuE_BF","H","H_"],

["Bushlat_VSRBut_EAST_Uniform","YuE_BBut","F","F_"],
["Bushlat_VSRNBut_EAST_Uniform","YuE_BnBut","F","F_"],
["BushlatVt_VSRBut_EAST_Uniform","YuE_BBut","CU","CU_"],
["BushlatVt_VSRNBut_EAST_Uniform","YuE_BnBut","CU","CU_"],
["BushlatVtk_VSRBut_EAST_Uniform","YuE_BBut","H","H_"],
["BushlatVtk_VSRNBut_EAST_Uniform","YuE_BnBut","H","H_"],

["Bushlat_VSRDub_EAST_Uniform","YuE_BDub","F","F_"],
["Bushlat_VSRNDub_EAST_Uniform","YuE_BnDub","F","F_"],
["BushlatVt_VSRDub_EAST_Uniform","YuE_BDub","CU","CU_"],
["BushlatVt_VSRNDub_EAST_Uniform","YuE_BnDub","CU","CU_"],
["BushlatVtk_VSRDub_EAST_Uniform","YuE_BDub","H","H_"],
["BushlatVtk_VSRNDub_EAST_Uniform","YuE_BnDub","H","H_"],

["Bushlat_VSRflo_EAST_Uniform","YuE_BFS","F","F_"],
["Bushlat_VSRNflo_EAST_Uniform","YuE_BnFS","F","F_"],
["BushlatVt_VSRflo_EAST_Uniform","YuE_BFS","CU","CU_"],
["BushlatVt_VSRNflo_EAST_Uniform","YuE_BnFS","CU","CU_"],
["BushlatVtk_VSRflo_EAST_Uniform","YuE_BFS","H","H_"],
["BushlatVtk_VSRNflo_EAST_Uniform","YuE_BnFS","H","H_"],

["Bushlat_VSR_EAST_Uniform","YuE_BVSR","F","F_"],
["Bushlat_VSRN_EAST_Uniform","YuE_BnVSR","F","F_"],
["BushlatVt_VSR_EAST_Uniform","YuE_BVSR","CU","CU_"],
["BushlatVt_VSRN_EAST_Uniform","YuE_BnVSR","CU","CU_"],
["BushlatVtk_VSR_EAST_Uniform","YuE_BVSR","H","H_"],
["BushlatVtk_VSRNflo_EAST_Uniform","YuE_BnVSR","H","H_"],

["Bushlat_VSRw_EAST_Uniform","YuE_BVSRw","F","F_"],
["Bushlat_VSRNw_EAST_Uniform","YuE_BnVSRw","F","F_"],
["BushlatVt_VSRw_EAST_Uniform","YuE_BVSRw","CU","CU_"],
["BushlatVt_VSRNw_EAST_Uniform","YuE_BnVSRw","CU","CU_"],
["BushlatVtk_VSRw_EAST_Uniform","YuE_BVSRw","H","H_"],
["BushlatVtk_VSRNw_EAST_Uniform","YuE_BnVSRw","H","H_"]
